StartupProject: D:\Coding\AxionEngine\Axion\AxionStudioProject\AxionStudio\Projects\ExampleProject\ExampleProject.axproj
Panels:
  - Name: SystemInfoPanel
    Visible: true
  - Name: SceneHierarchyPanel
    Visible: true
  - Name: EditorCameraPanel
    Visible: true
  - Name: ContentBrowserPanel
    Visible: true
    ThumbnailSize: 92
    OnlyAssetFiles: true
    ShowExtensions: false
  - Name: ProjectPanel
    Visible: true
  - Name: SceneOverviewPanel
    Visible: true
  - Name: AssetManagerPanel
    Visible: true